# Generated by Django 4.2.5 on 2024-01-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('year_of_manufacture', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'car_data',
            },
        ),
    ]
